### ISSUE TITLE
One hot encoding

### ISSUE THREAD

**Issue by wilhelmssonjens** [IVL-Research/Open-Waters#19]
One hot encoding - for converting categorical data to multiple columns with ones and zeros.
This should be implemented if it is used for the scorewater project - @mrg20 to answer this along with usage examples.

![image](https://user-images.githubusercontent.com/72920665/99668650-51ad1980-2a6e-11eb-95f9-5bf4de4e437a.png)

**Comment by mrg20** [comment]
Example from: https://www.geeksforgeeks.org/ml-one-hot-encoding-of-datasets-in-python/
The idea of the example is to convert a categorical column with fruits names into a binary column for each fruit.

Another example would be the encoding of different European countries:

```
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

ids = [11, 22, 33, 44, 55, 66, 77]
countries = ['Spain', 'France', 'Spain', 'Germany', 'France']

df = pd.DataFrame(list(zip(ids, countries)),
                  columns=['Ids', 'Countries'])

y = OneHotEncoder().fit_transform(df).toarray()
print(y)
```
The print would output:
```
[[1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]]
```
