### ISSUE TITLE
Out of range function not marking all out of range values with circles

### ISSUE THREAD

**Issue by wilhelmssonjens** [IVL-Research/Open-Waters#9]
Not all out of range values produced by out_of_range_detection are marked with a circle, see attachment.

![image](https://user-images.githubusercontent.com/72920665/97270251-24829800-182f-11eb-947c-c141f68eefed.png)

**Comment by joelwanemark** [comment]
Can not reproduce error.
Lower limit = 1
![image](https://user-images.githubusercontent.com/28628888/97313391-d8ebe080-1866-11eb-9bda-89da5486f5ff.png)

**Comment by wilhelmssonjens** [comment]
I'll close this issue and if the issue shows up again we can reopen it.
